---

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Filesystem
      - id: check-case-conflict
      - id: check-symlinks
      # Whitespace
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v0.15.3
    hooks:
      - id: stylua
