require "mark.editor.autopairs"
require "mark.editor.bufferline"
require "mark.editor.colorscheme"
require "mark.editor.cmp"
require "mark.editor.nvim-tree"
require "mark.editor.telescope"
require "mark.editor.toggleterm"
require "mark.editor.winbar"
